//Students Endpoints:
const STUDENT_PROFILE = 'student:STUDENT_PROFILE'

//Professor Endpoints:
const PROFESSOR_PROFILE = 'professor:PROFESSOR_PROFILE'
const UPDATE_PROFESSOR = 'admin:UPDATE_PROFESSOR'
const DELETE_PROFESSOR = 'admin:DELETE_PROFESSOR'
const ADD_EXAM = 'professor:ADD_EXAM'
const SHOW_EXAMS = 'professor:SHOW_EXAMS'
const UPDATE_EXAM = 'professor:UPDATE_EXAM'
const DELETE_EXAM = 'professor:DELETE_EXAM'
// Admin Endpoints:
const GET_ALL_STUDENT = 'admin:GET_ALL_STUDENT'
const GET_ALL_PROFESSOR = 'admin:GET_ALL_PROFESSOR'
const UPDATE_STUDENT = 'admin:UPDATE_STUDENT'
const DELETE_STUDENT = 'admin:DELETE_STUDENT'

module.exports = {
    STUDENT_PROFILE,
    GET_ALL_STUDENT,
    UPDATE_STUDENT,
    DELETE_STUDENT,
    PROFESSOR_PROFILE,
    GET_ALL_PROFESSOR,
    UPDATE_PROFESSOR,
    DELETE_PROFESSOR,
    ADD_EXAM,
    SHOW_EXAMS,
    UPDATE_EXAM,
    DELETE_EXAM,
}
