const {
    GET_ALL_STUDENT,
    UPDATE_STUDENT,
    DELETE_STUDENT,
    GET_ALL_PROFESSOR,
    UPDATE_PROFESSOR,
    DELETE_PROFESSOR,
    GET_ALL_EXAMS,
} = require('../../endpoints')

module.exports = [
    GET_ALL_STUDENT,
    GET_ALL_PROFESSOR,
    UPDATE_STUDENT,
    DELETE_STUDENT,
    UPDATE_PROFESSOR,
    DELETE_PROFESSOR,
    GET_ALL_EXAMS,
]
