const {
    PROFESSOR_PROFILE,
    ADD_EXAM,
    MY_EXAMS,
    UPDATE_EXAM,
    DELETE_EXAM,
    ADD_QUESTIONS,
    UPDATE_QUESTION,
    DELETE_QUESTION,
} = require('../../endpoints')

module.exports = [
    PROFESSOR_PROFILE,
    ADD_EXAM,
    MY_EXAMS,
    UPDATE_EXAM,
    DELETE_EXAM,
    ADD_QUESTIONS,
    UPDATE_QUESTION,
    DELETE_QUESTION,
]
